### PR TITLE
Factory

### PR DESCRIPTION
**Pull request by loicgasser**
Here is a first pre-version that contains all we need for chsdi.

Overall it corrects:
- Polygon and MultiPolygons with holes, those were not correctly represented before in esrijson
- Default representation according to spec
- wkid parameter can be used to define the spatialReference in the geometry field
- We now have a unique to_shape function that transforms any esrijson object into a shapely geometry (used to perform geometric operations in chsdi) avoiding the unnecessary try except hack we currently have in chsdi.
- We can now also remove papyrus (we use only one function that we overload)

### CODE REVIEW

**Comment by gjn** [comment]
Can we adapt the repository according to our naming convention? https://github.com/geoadmin/doc-guidelines/blob/master/NAMES.md

**Comment by loicgasser** [comment]
Repo name lib-esrijson and py module name esrijson.

**Comment by loicgasser** [comment]
I will adapt the other repos names as well. We now have a couple.

**Comment by loicgasser** [comment]
Wouldn t the python-, node- etc... prefix be more suited for that? I imagine we may have node modules in the future as well.

**Pull request merged**
